### ISSUE TITLE
Consolidated view?

### ISSUE THREAD

**Issue by torinedge** [lennykean/MiningMonitor#6]
Running Windows install to monitor a local miner and two remotes (TeamredMiner exposing Claymore API). Any plans for a consolidated monitor view instead of each miner individually?

Happy to contribute if you have a pay portal set up.

**Comment by lennykean** [comment]
I like the idea, and its should be pretty straight forward to implement. I'll probably get a new build out soon with that feature.

**Comment by lennykean** [comment]
Good suggestion. [version 0.9.107](https://github.com/lennykean/MiningMonitor/releases/tag/MiningMonitor-v0.9.107) has this feature
